# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: InvokeRESTAPI@1
  inputs:
    method: 'POST' 
    Options: POST
    headers: '{"Content-Type": "application/json"}'
    body: '{"api_definition":{"swagger":"2.0","info":{"description":"Provides third parties with a view of the consents that they have been granted by end users.\n  ","version":"1.0.0","title":"Account Details 2","versions":"Test"},"host":"api-consent-details-service.apps.pcf-t01-we.rabobank.nl","basePath":"/","tags":[{"name":"consent-end-point","description":"Consent End Point"}],"paths":{"/consents":{"get":{"tags":["consent-end-point"],"summary":"Get consent details","description":"Returns the scope and products associated with the consent object","operationId":"getConsentDetailsUsingGET","produces":["application/json"],"parameters":[{"name":"X-API-Confirmation-Code","in":"header","description":"X-API-Confirmation-Code","required":true,"type":"string"}],"responses":{"200":{"description":"Successfully retrieved consent details","schema":{"$ref":"#/definitions/Consent"}},"500":{"description":"Technical error. Unable to retrieve consent details"}}}}},"definitions":{"AccountReference":{"type":"object","required":["currency","iban"],"properties":{"currency":{"type":"string","example":"EUR","description":"Currency code, as per ISO 4217."},"iban":{"type":"string","example":"NL01RABO0123456789","description":"An International Bank Account Number, as per ISO 13616."}},"title":"AccountReference","description":"Details of consented products"},"Consent":{"type":"object","required":["access"],"properties":{"access":{"type":"object","example":{"ais.balances.read":[{"iban":"NL01RABO0123456789","currency":"EUR"},{"iban":"NL02RABO0234567891","currency":"EUR"}],"ais.transactions.read-history":[{"iban":"NL02RABO0234567891","currency":"EUR"},{"iban":"NL03RABO0345678912","currency":"EUR"}],"ais.transactions.read-90days":[{"iban":"NL04RABO0456789123","currency":"EUR"}]},"description":"An associative array relating scopes (field names) to consented products (values).","additionalProperties":{"type":"array","items":{"$ref":"#/definitions/AccountReference"}}},"validUntil":{"type":"string","example":"9999-12-31","description":"Date at which this consent expires, as per section 5.6 of RFC 3339."}},"title":"Consent","description":"Consent details object"}}}}'
    urlSuffix: https://api-validator-service-dev.apps.pcf-t01-we.rabobank.nl/api-violations/all
